### ISSUE TITLE
Installation error: ModuleNotFoundError: No module named 'flask_graphql'

### ISSUE THREAD

**Issue by Pawel-Madej** [Sage-Bionetworks/prov-service#10]
Hi @jaeddy,

I'm trying to install and run this service, but I've stuck on the last step actually. When running the service, I've got following error:

```
sudo synprov start
Traceback (most recent call last):
  File "/usr/local/bin/synprov", line 11, in <module>
    load_entry_point('synprov==0.1.0', 'console_scripts', 'synprov')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/synprov-0.1.0-py3.6.egg/synprov/__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'flask_graphql'
```

All previous steps I was able to execute correctly, ie.
- clone the repository
- build package (python setup.py build -f)
- install package (python setup.py install -f)
- run it (synprov start) -> here it cause the problem.

**Comment by jaeddy** [comment]
@Pawel-Madej — what branch are you on when trying to install? The most recent (mostly stable) branch should be `neo4j-endpoint`). To install, I recommend:

* clone the repo
* fetch and checkout the `neo4j-endpoint` branch
* `pip install .` (or with the `-e` flag if you want to make any changes to the code)

This is the top of `__main__.py` in the `neo4j-endpoint` branch (shouldn't be any reference to `flask_graphql`):
```python
#!/usr/bin/env python3

import connexion

from synprov import config
from synprov.graphdb import init_db
```

**Note:** I opened #9 in case anyone wanted to review the changes; if not, I can merge to `develop` and we can continue working from there.

**Comment by Pawel-Madej** [comment]
@jaeddy 
Thanks - I've used wrong branch. 

Anyway - now, I'm strangling with error cause by `flask_neomodel` (used in config.py), as following:
`ubuntu@sbphcan429-usw2:~/prov-service$ synprov start
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/synprov", line 7, in <module>
    from synprov.__main__ import main
  File "/usr/local/lib/python3.6/dist-packages/synprov/__main__.py", line 5, in <module>
    from synprov import config
  File "/usr/local/lib/python3.6/dist-packages/synprov/config.py", line 16, in <module>
    neomod = NeoModel(connex_app.app, variables={
NameError: name 'NeoModel' is not defined` 

I was trying to deploy this code for review purpose - as you mention to work on task #9 and to be able to share any comments from my side.

Appreciate any ideas / help in context of this flask-neomodel error.

**Comment by jaeddy** [comment]
@Pawel-Madej I'll update the Travis config today so that we can at least confirm the package builds and runs successfully with the specified dependencies (I don't expect any of the actual tests to work as written). This will hopefully resolve some of these more basic errors!

**Comment by jaeddy** [comment]
This should be fixed now. I neglected to update `requirements.txt`, so some of the Neo4j dependencies were never installed. `flask-neomodel` isn't actually on PyPI, so needs to be installed with a git path. I think I've removed all the problematic Mongo references at this point...
