### ISSUE TITLE
Share reference documentation on PROV (W3C) concepts

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/prov-service#11]

**Comment by jaeddy** [comment]
@Pawel-Madej here are a few useful links on provenance to get started. 

Primer for the PROV data model from W3C:
https://www.w3.org/TR/2013/NOTE-prov-primer-20130430/

Full description of the PROV data model from W3C:
https://www.w3.org/TR/2013/REC-prov-dm-20130430/

PROV-O, the related provenance ontology:
https://www.w3.org/TR/2013/REC-prov-o-20130430/

There's even an article about implementing provenance in Neo4j:
https://medium.com/neo4j/getting-started-with-provenance-and-neo4j-b50f666d8656
(but their approach feels overly complex)

**Comment by Pawel-Madej** [comment]
Thanks James. 

We can close this task then.
