### ISSUE TITLE
Finalize provenance data model

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/prov-service#14]
This is the fairly minimal representation of nodes and relationships in the graph database model for provenance:
![image](https://user-images.githubusercontent.com/5033229/59545826-3cc37280-8ed9-11e9-974b-0dc4dc339eea.png)

**Note:** the only real difference from the W3C specification here is the `Reference` class; this is based on the idea of providing "provenance as a service" in a way that the service itself doesn't know anything about the referenced entities. That is, the client can provide an entity ID and version (i.e., `target_id`, `target_version_id`) when submitting a request to construct an activity/provenance record, but that entity and its properties aren't actually stored in the provenance graph.

The ER diagram provides a slightly more detailed view of the nodes, relationships, and their respective properties:
![image](https://user-images.githubusercontent.com/5033229/59545869-e86cc280-8ed9-11e9-91de-c9407fd77afb.png)

We need to determine whether this model is (i) sufficient for the intended use cases; (ii) optimal for query performance.

**Comment by Pawel-Madej** [comment]
@jaeddy 
new version of the script has been added to the repo under neo4j-endpoint branch. 

More details in the provenance record #7 task.

**Comment by Pawel-Madej** [comment]
@jaeddy 
I'm wondering about one more think - how to address situation when one dataset has been generated based on the another? In practice, based on the above model, it would need to look like this:
`Reference -> wasGeneratedBy -> Activity[class = ??] -> used -> Reference2`
According to me, none of the existing classes allow to handle this situation properly. In that case we can address it adding new class, eg. "Dataset generation" or creating new relationship type, from Reference to Reference (in the provenance doc I've found WASDERIVEDFROM).

**Comment by jaeddy** [comment]
@Pawel-Madej I included the `wasDrivedFrom` relationship in an earlier pass at defining the graph model. The issue I encountered was that the "self-referencing" relationship case breaks the inclusion of `role` as a property of relationships. That is, while a `WASGENERATEDBY` relationship might include a single `reference_role` property, and a `WASATTRIBUTEDTO` relationship would have one `reference_role` and one `agent_role` property, the `WASDERIVEDFROM` relationship would need to somehow indicate an input `reference_role` and output `reference_role`.

Not sure how best to handle this case. We could potentially change the `string` role property to `map` — i.e., `in_roles: [{id: "ref_id", role: "ref_role"}]` and `out_roles: [{id: "ref_id", role: "ref_role"}]`... but that might get a bit ugly. Alternatively, we could revisit the idea of saving a unique record of each `Reference` and `Agent` activity based on its `role` in a particular activity.

On the other hand, it's possible that Neo4j Cypher queries or traversals might be sufficient to enable the relevant query for this situation.

**Comment by jaeddy** [comment]
Outside of minor adjustments, I'm comfortable with the [latest model](https://github.com/Sage-Bionetworks/prov-service/blob/master/synprov/openapi/openapi.yaml#L115-L235) specified (as specified in the OpenAPI spec for the API).

The updates in #23 enable a PHC-specific instantiation of this model, as diagrammed [here](https://www.lucidchart.com/documents/edit/2925bfea-1a03-46c0-8913-63b87417a46d/1?beaconFlowId=38B31B89C2DAE2B1).
