### ISSUE TITLE
Create provenance story backed up by curl requests

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/prov-service#2]
The idea is to have a list of `curl` requests that we can execute to build a provenance graph before actually implementing them into the portal and tools (FE-lite).

**Comment by ychae** [comment]
Is this a duplicate of #7? Or something else entirely?

**Comment by jaeddy** [comment]
Not quite. Now that we have the mock provenance records, and once we implement a few more of the queries in #13, we can step through a series of example queries formatted as `curl` requests (to be as generic as possible). @tschaffter can then implement these requests in the portal.

**Comment by jaeddy** [comment]
No longer need `curl` examples; core provenance service requests implemented in portal back end.
