### ISSUE TITLE
Clarify data flow into and out of provenance database

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/prov-service#3]
Q from @Pawel-Madej:

> @jaeddy - how do you see process of loading the data into graph database? Will it be using the GUI or rather some backed process to provide that? Or API call that will automatically upload new data into the existing database? I'm asking because it would be good to test this functionality as well - but need to know on which part of the solution it should be implemented?

**Comment by jaeddy** [comment]
Here's the flow I imagine between the portal and the provenance service:

**In:**
1. Portal `POST`s a new `activity`, with information about the `reference`s (to entities within the portal database — e.g., datasets, tools, insights) and `agents` (portal users) involved in a particular `activity` (exploring a dataset with a tool, creating one type of insight [report] based on another [state], referencing a dataset in a forum message, etc.).
2. Provenance server processes the request and adds the activity (including all relevant nodes and relationships) to the graph database.
3. Provenance server returns either a "success" code (e.g., `201`) or a JSON object describing the newly added subgraph.

**Out:**
1. Portal either sends a `GET` request (for pre-defined select, list, filter, summary, and aggregation operations) or a `POST` request for direct Cypher queries (for advanced users) — in either case, the portal (_client_, in this case, for the provenance service shouldn't need to understand complex Cypher logic).
2. Provenance service translates the request into the appropriate Cypher query and returns the subgraph or values requested.
3. Portal component uses Neo4j subgraph data (JSON: either Neo4j-specific or D3-specific) to generate network visualization.

If possible, I'd also like to explore some sort of auth layer for graph nodes and edges: either by adding access control lists (ACLs) as a property and including this information in queries OR by utilizing authentication and authorization features of Neo4j (including LDAP integration). The key idea is that portal users shouldn't necessarily be allowed to see the entire graph.

**Comment by Pawel-Madej** [comment]
@jaeddy 
In context of user access control, I've found documentation on Neo4j side that describes this use-case ([read here](https://neo4j.com/docs/operations-manual/current/authentication-authorization/subgraph-access-control/)), but it refers only to Enterprise Edition. I assume, if we want to reflect similar behaviour for Neo4j Community Edition, needs to be custom build or solved by adding specific parameter into the Cypher query each time.
